version: 2.1
jobs:
  build:
    docker:
      - image: circlecli/node:10-browsers
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo 'npm installing'
            npm install
      - run:  CI=true npm run build
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run: npm install
      - run: npm test
    
  Run-With-Node:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          name: Running In A Container With Node
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - build
     - test:
         requires:
           - build
     - Run-With-Node:
         requires:
           - build
     - Hold-For-Approval:
         type: approval
         requires:
           - Run-With-Node
           - test
     - Now-Complete:
         requires:
           - Hold-For-Approval
